[package]
name = "skv"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.8", features = ["derive"] }
aes-gcm = "0.9.4"
regex = "1.5"
fastrand = "1.8.0"
hex = "0.4.3"
